title: Securing your workflows
tagline: Keep your code safe, sound, and secure in GitHub repositories
description: Learn security best practices and keep your project’s contributions—and contributors—safe.
tags:
  - Git
  - GitHub
template:
    name: security-on-github
    repo: security-template
preferences:
- type: dropdown
  name: language
  label: Language
  description: Choose your preferred language.
  options:
  - label: English
    value: en
  - label: 日本語
    value: ja
before:
  - type: updateBranchProtection
  - type: createPullRequest
    title: Update the vulnerable dependency
    body: 03_update-dependency.md
    head: update-dependency
  - type: octokit
    method: 'repos.get'
    owner: '%payload.repository.owner.login%'
    repo: '%payload.repository.name%'
    action_id: gotten_repo
  - type: createIssue
    title: Welcome
    body: 01a_class-introduction-issue.md
    data:
      private: '%actions.gotten_repo.data.private%'
  - type: createPullRequest
    title: Add a `.gitignore` file
    body: 04b_add-gitignore.md
    head: add-gitignore

steps:
  - title: Enable repository settings
    description: Enable settings in your repository for the next activities.
    translations:
      ja:
        title: リポジトリの設定を有効化しよう
        description: 次のステップのためにリポジトリの設定を有効化しましょう。
    event: page_build
    link: '{{ repoUrl }}/issues/2'
    actions:
      - type: createIssue
        title: Find repository vulnerabilities
        body: 02_find-vulnerabilities.md
        action_id: issue
      - type: closeIssue
        issue: Welcome
      - type: octokit
        method: repos.getPages
        owner: '%payload.repository.owner.login%'
        repo: '%payload.repository.name%'
        action_id: pagesUrl
      - type: respond
        issue: Welcome
        with: 02_closed-issue.md
        data:
          url: '%actions.issue.data.html_url%'
          pages: '%actions.pagesUrl.data.html_url%'

  - title: Find the vulnerable dependency
    description: Find the vulnerable dependency, and comment with the suggested update version.
    translations:
      ja:
        title: 脆弱性のある依存関係を見つけよう
        description: 脆弱性のある依存関係と、推奨バージョンのコメントを見つけましょう。
    event: issue_comment.created
    link: '{{ repoUrl }}/issues/4'
    actions:
      - type: respond
        with: 03_found-vulnerability.md
      - type: closeIssue
        issue: Find repository vulnerabilities

  - title: Update the dependency version
    description: Edit the file in the pull request to update the dependency.
    translations:
      ja:
        title: 依存関係のバージョンを更新しよう
        description: 依存関係のバージョンを更新するためにプルリクエストを使ってファイルを編集しましょう。
    event: pull_request.synchronize
    link: '{{ repoUrl }}/pull/1'
    actions:
      - type: getFileContents
        action_id: fileContents
        filename: package.json
      - type: gate
        left: '/"debug": "[\^\~\>]?\=?\d+\.\d+\.\d+"/g'
        operator: test
        right: '%actions.fileContents%'
        else:
        - type: respond
          issue: 3
          with: 03_adding-bad-changes.md
      - type: removeBranchProtection
      - type: respond
        with: 03_good-pr.md

  - title: Merge your pull request
    description: Merge the pull request you've opened to update the vulnerability dependency.
    translations:
      ja:
        title: プルリクエストをマージしよう
        description: 脆弱性のある依存関係を更新するためにオープンしたプルリクエストをマージしましょう。
    event: pull_request.closed
    link: '{{ repoUrl }}/pull/1'
    actions:
      - type: gate
        left: '%payload.pull_request.merged%'
        else:
          - type: octokit
            method: issues.edit
            state: open
            owner: '%payload.repository.owner.login%'
            repo: '%payload.repository.name%'
            number: '%payload.repository.pull_request.number%'
          - type: respond
            with: 03_accidental-close.md
      - type: updateBranchProtection
      - type: respond
        with: 04a_good-merge.md

  - title: Add to the `.gitignore` file
    description: The `.gitignore` file is ready to be edited in an open pull request. Add the `.env` file to the `.gitignore` file.
    translations:
      ja:
        title: プルリクエストで `.gitignore` ファイルに追記しよう
        description: オープンしたプルリクエストを使って `.gitignore` ファイルを更新する準備ができました。 .env` ファイルを `.gitignore` に追加しましょう。
    event: pull_request.synchronize
    link: '{{ repoUrl }}/pull/3'
    actions:
      - type: getFileContents
        action_id: fileContents
        filename: .gitignore
      - type: gate
        left: '/\.env/m'
        operator: test
        right: '%actions.fileContents%'
        else:
        - type: respond
          with: 05_fail-ignore.md
      - type: removeBranchProtection
      - type: respond
        with: 05_good-ignore.md

  - title: Merge the pull request
    description: Merge the second pull request with updates to the `.gitignore` file.
    translations:
      ja:
        title: プルリクエストをマージしよう
        description: 2つ目のプルリクエストをマージして `.gitignore` ファイルを更新しよう
    event: pull_request.closed
    link: '{{ repoUrl }}/pull/3'
    actions:
      - type: gate
        left: '%payload.pull_request.merged%'
        else:
          - type: octokit
            method: issues.edit
            state: open
            owner: '%payload.repository.owner.login%'
            repo: '%payload.repository.name%'
            number: '%payload.repository.pull_request.number%'
          - type: respond
            with: 05_early-close.md
      - type: octokit
        method: repos.getPages
        owner: '%payload.repository.owner.login%'
        repo: '%payload.repository.name%'
        action_id: pagesUrl
      - type: createIssue
        title: Congratulations!
        body: 06b_final-issue.md
        data:
          url: '%actions.pagesUrl.data.html_url%'
        action_id: finalIssue
      - type: respond
        with: 06a_nice-merge.md
        data:
          url: '%actions.finalIssue.data.html_url%'
