title: Building Secure Repositories on GitHub
tagline: # TODO ??
description: Your projects are important, and so is security. Use GitHub's security features along with best practices to keep your code (and those who use it) safe.
template:
    name: # TODO reviewing-pull-requests
    url: # TODO https://github.com/githubtraining/review-pull-requests-template.git
before:
  - type: updateBranchProtection
  - type: createIssue
    title: Welcome
    body: 01_class-introduction-issue.md
steps:
  - title: Close first issue
    description: After you enable GitHub Security features in your repository, close this issue.
    event: issues.closed
    link: https://github.com/{{ course.Organization.login }}/{{ registration.repositoryName }}/issues/1
    actions:
      - type: createIssue
        title: Find repository vulnerabilities
        body: 02_find-vulnerabilities.md
      - type: respond
        with: 02_closed-issue.md
        data:
          url: '%actions.issue.data.html_url%'

  - title: Open a pull request
    description: Open a pull request to update the dependency.
    event: pull_request.opened
    link: https://github.com//{{ course.Organization.login }}/{{ registration.repositoryName }}/pull/3
    actions:
      - type: gate
        # TODO check the ping from the webhook event of a vulnerability being recognized (does this need to happen earlire?) and store it
        # TODO make sure there is an open pull request, and dependency is updated properly, comparing with updated information stored earlier
        # TODO if yes, approve PR and reply with 03_good-pr.md
        # TODO if no, request changes and give more instructional help (03-adding-bad-changes.md)
        # TODO If closed early, comment and reopen (03_accidental-close.md)

  - title: Merge your pull request
    description: Merge the pull request you've opened to update the vulnerability dependency.
    event: pull_request.closed
    link: https://github.com/{{ course.Organization.login }}/{{ registration.repositoryName }}/pull/3
    actions:
      - type: gate
        left: '%payload.pull_request.merged%'
      - type: respond
        with: 04_good-merge.md
      - type: createPullRequest
        title: Add a `.gitignore` file
        body: 04_add-gitignore.md
        head: # TODO tbd, branch adding `.gitignore` file

  - title: Add to the `.gitignore` file
    description: The `.gitignore` file is ready to be edited in an open pull request. Add the `.env` file to the `.gitignore` file.
    event: push
    link: https://github.com/{{ course.Organization.login }}/{{ registration.repositoryName }}/pull/3
    actions:
      - type: getFileContents
        action_id: fileContents
        filename: .gitignore
      - type: gate
        left: '/^.env/m'
        operator: test
        right: '%actions.fileContents%'
        else:
        - type: respond
          with: 05_fail-ignore.md
      - type: respond
        with: 05_good-ignore.md
        # TODO Reopen if closed and reply with (05_early-close.md)

  - title: Merge the pull request
    description: Merge the second pull request with updates to the `.gitignore` file
    event: pull_request.closed
    link: https://github.com/{{ course.Organization.login }}/{{ registration.repositoryName }}/pull/4
    actions:
      - type: gate
        left: '%payload.pull_request.merged%'
      - type: respond
        with: 06_nice-merge.md
      - type: createIssue
        title: Congratulations!
        body: 06_final-issue.md
        data:
          url: 'https://%user.username%.github.io/%payload.repository.name%'
