title: # TODO Reviewing Pull Requests
tagline: # TODO Start collaborating for GitHub, with GitHub.
description: # TODO Learn how GitHub uses pull request reviews to communicate and collaborate during the development process.
template:
    name: # TODO reviewing-pull-requests
    url: # TODO https://github.com/githubtraining/review-pull-requests-template.git
before:
  - type: updateBranchProtection
  - type: createIssue
    title: Welcome
    body: 01_class-introduction-issue.md
steps:
  - title: Close first issue
    description: # TODO, Enable settings, and close issue
    event: # TODO
    link: # TODO https://github.com/{{ course.Organization.login }}/{{ registration.repositoryName }}/issues/1
    actions:
      - type: gate
        # TODO closed issue
      - type: respond
        with: 02_closed-issue.md
      - type: # TODO open new issue
        body: 02_find-vulnerabilities.md


  - title: Open a pull request
    description: # TODO
    event: # TODO
    link: # TODO https://github.com//{{ course.Organization.login }}/{{ registration.repositoryName }}/pull/2
    actions:
      - type: gate
        # TODO make sure there is an open pull request, and dependency is updated properly
        # TODO if yes, approve PR and reply with 03_good-pr.md
        # TODO if no, request changes and give more instructional help (03-adding-bad-changes.md)
        # TODO If closed early, comment and reopen (03_accidental-close.md)

  - title: Merge the pull request
    description: # TODO
    event: # TODO pull_request_review.submitted
    link: # TODO https://github.com/{{ course.Organization.login }}/{{ registration.repositoryName }}/pull/2
    actions:
      - type: gate
        # TODO Make sure PR is merged
      - type: # TODO comment on merged PR with 04_good-merge.md
      - type: # TODO open new PR
        body: 04_add-gitignore.md
        head: # TODO tbd, branch adding `.gitignore` file

  - title: Add `.env` to the `.gitignore` file
    description: # TODO
    event: # TODO pull_request_review.submitted
    link: # TODO https://github.com/{{ course.Organization.login }}/{{ registration.repositoryName }}/pull/3
    actions:
      - type: gate
        # TODO check to make sure that user commits adding .env to .gitignore file
      - type:
        # TODO Approve if good and respond with (05_good-ignore.md)
        # TODO Request changes if not good with (05_fail-ignore.md)
        # TODO Reopen if closed and reply with (05_early-close.md)

  - title: Merge the pull request with the `.gitignore`
    description: # TODO
    event: # TODO pull_request_review.submitted
    link: # TODO https://github.com/{{ course.Organization.login }}/{{ registration.repositoryName }}/pull/3
    actions:
      - type: gate
        # TODO make sure they merged
      - type: respond
        with: 06_nice-merge.md
      - type: createIssue
        title: Congratulations!
        body: 06_final-issue.md
        data:
          url: 'https://%user.username%.github.io/%payload.repository.name%'
